name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          token: ${{ secrets.GH_TOKEN}}

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.34.6  
        with:
          github_token: ${{ secrets.GH_TOKEN }}
